platform :ios, "9.0"

use_frameworks!

def memory_leaks
  pod 'MLeaksFinder', :configurations => ['Debug']
end

def fz_library
  pod 'FZObserver'
  pod 'FZRouterSwift'
end

target 'FZBuildingBlock_Example' do
  pod 'FZBuildingBlock', :path => '../'
  
  memory_leaks
  fz_library

  target 'FZBuildingBlock_Tests' do
    inherit! :search_paths

    
  end
end
