platform :ios, "10.0"

use_frameworks!

def memory_leaks
  # 正常指定版本 1.0.0 的没有移除 FBRetainCycleDetector
  # 需要手动指定 :git => 'https://github.com/Tencent/MLeaksFinder.git'
  pod 'MLeaksFinder', :configurations => ['Debug'], :git => 'https://github.com/Tencent/MLeaksFinder.git'
end

def fz_library
  pod 'FZObserver'
  pod 'FZRouterSwift'
  pod 'FZWeakProxy'
  pod 'FZTheme'
end

target 'FZBuildingBlock_Example' do
  pod 'FZBuildingBlock', :path => '../'
  
  memory_leaks
  fz_library

  target 'FZBuildingBlock_Tests' do
    inherit! :search_paths

    
  end
end
