platform :ios, "9.0"

use_frameworks!

target 'FZBuildingBlock_Example' do
  pod 'FZBuildingBlock', :path => '../'
  
  pod 'MLeaksFinder'
  
  target 'FZBuildingBlock_Tests' do
    inherit! :search_paths

    
  end
end
